CITIES = "Atlanta+GA
      |Orlando+FL
      |Charleston+SC
      |Denver+CO
      |Washington+DC
      |New+Orleans+LA
      |New+York+NY
      |Asheville+NC
      |Chicago+IL
      |Indianapolis+IN
      |Jackson+WY
      |Miami+FL
      |Los+Angeles+CA
      |Phoenix+AZ
      |Austin+TX
      |San+Francisco+CA
      |Portland+OR
      |Las+Vegas+NV
      |Nashville+TN
      |Montreal+QC
      |Toronto+ON
      |Huntsville+AL
      |Greenville+SC"
